// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Provides personalized tips for saving money based on spending habits.
 *
 * - getSpendingTips - A function that returns personalized spending tips.
 * - SpendingTipsInput - The input type for the getSpendingTips function.
 * - SpendingTipsOutput - The return type for the getSpendingTips function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const SpendingTipsInputSchema = z.object({
  expenseSummary: z.string().describe('A summary of the user\'s expenses, broken down by category and time period.'),
  budgetSettings: z.string().describe('The user\'s monthly budget for each expense category.'),
  spendingComparison: z.string().describe('A comparison of the user\'s actual spending against their set budget for each category.'),
});
export type SpendingTipsInput = z.infer<typeof SpendingTipsInputSchema>;

const SpendingTipsOutputSchema = z.object({
  tips: z.string().describe('Personalized tips for saving money based on the user\'s spending habits.'),
});
export type SpendingTipsOutput = z.infer<typeof SpendingTipsOutputSchema>;

export async function getSpendingTips(input: SpendingTipsInput): Promise<SpendingTipsOutput> {
  return spendingTipsFlow(input);
}

const spendingTipsPrompt = ai.definePrompt({
  name: 'spendingTipsPrompt',
  input: {
    schema: z.object({
      expenseSummary: z.string().describe('A summary of the user\'s expenses, broken down by category and time period.'),
      budgetSettings: z.string().describe('The user\'s monthly budget for each expense category.'),
      spendingComparison: z.string().describe('A comparison of the user\'s actual spending against their set budget for each category.'),
    }),
  },
  output: {
    schema: z.object({
      tips: z.string().describe('Personalized tips for saving money based on the user\'s spending habits.'),
    }),
  },
  prompt: `You are a personal finance advisor. Analyze the user's spending habits and provide personalized tips for saving money.

Here is a summary of the user's expenses:
{{expenseSummary}}

Here are the user's budget settings:
{{budgetSettings}}

Here is a comparison of the user's actual spending against their set budget:
{{spendingComparison}}

Based on this information, provide personalized tips for saving money.`, 
});

const spendingTipsFlow = ai.defineFlow<
  typeof SpendingTipsInputSchema,
  typeof SpendingTipsOutputSchema
>({
  name: 'spendingTipsFlow',
  inputSchema: SpendingTipsInputSchema,
  outputSchema: SpendingTipsOutputSchema,
}, async (input) => {
  const {output} = await spendingTipsPrompt(input);
  return output!;
});
